# Generated by Django 2.2.12 on 2020-04-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=50)),
                ('jenis_kelamin', models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], default='Laki-laki', max_length=30)),
                ('tanggal_lahir', models.CharField(max_length=50)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('no_tlp', models.CharField(max_length=18)),
                ('email', models.EmailField(max_length=254)),
                ('posisi', models.CharField(choices=[('Web Developer', 'Web Developer'), ('IT Support', 'IT Support'), ('Back-end', 'Back-end')], default='Web Developer', max_length=50)),
                ('date_input', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
        ),
    ]
