# Generated by Django 2.2.12 on 2020-04-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posisi', models.CharField(max_length=50)),
                ('syarat1', models.CharField(max_length=100)),
                ('syarat2', models.CharField(max_length=100)),
                ('syarat3', models.CharField(max_length=100)),
                ('syarat4', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('benefit', models.TextField()),
                ('kontak', models.TextField()),
                ('publish', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
        ),
    ]
